name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        elixir: ['1.8.0', '1.8.2', '1.9.4', '1.10.4', '1.10.x']
        include:
        - elixir: '1.8.0'
          otp: '21.x'
        - elixir: '1.8.2'
          otp: '21.x'
        - elixir: '1.9.4'
          otp: '22.x'
        - elixir: '1.10.4'
          otp: '22.x'
        - elixir: '1.10.x'
          otp: '23.x'
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
    - name: Run Credo
      run: mix credo --strict
    - name: Run Dialyzer
      run: mix dialyzer
